In [131]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn import metrics
from sklearn import linear_model

In [132]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import math
%matplotlib inline

In [133]:
df = pd.read_csv("F:\Computer Programming\Python-dev\Oil3Data.csv", sep = ",")
df = df.dropna(axis = 0)

In [134]:
#Get rid of price change outliers
df1 = df[df.Price_change > 0.1]
df2 = df[df.Price_change < -0.1]
df3 = pd.concat([df1, df2]).drop_duplicates(keep = False)
df = pd.concat([df, df3]).drop_duplicates(keep = False)

In [135]:
#Get rid of stock change outliers
df1 = df[df.Stock_change > 0.015]
df2 = df[df.Stock_change < -0.015]
df3 = pd.concat([df1, df2]).drop_duplicates(keep = False)
df = pd.concat([df, df3]).drop_duplicates(keep = False)

In [136]:
#plt.scatter(df['Stock_change'], df['Price_change'])

In [137]:
#1. Split the dataset into training and testing
#2. Build a function for the evaluation process
#3. Build a function for the evaluation of each datapoint
#4. Build a function for model evaluation
df = df.iloc[::-1]

In [138]:
train = df[0:1224]
test = df[1224: 1530]
print(train)
print(test)

           Date    Stock  Stock_change   Price  Price_change
1610  1/12/1990  1013190      0.008823   22.57     -0.030082
1609  1/19/1990  1019846      0.006569   22.73      0.007089
1608  1/26/1990  1032697      0.012601   22.11     -0.027277
1606   2/9/1990  1053257      0.002415   22.21     -0.022877
1605  2/16/1990  1052636     -0.000590   22.25      0.001801
...         ...      ...           ...     ...           ...
332   7/11/2014  1092592      0.001123  102.60     -0.021086
331   7/18/2014  1097829      0.004793  101.68     -0.008967
330   7/25/2014  1097336     -0.000449  103.26      0.015539
329    8/1/2014  1089228     -0.007389   99.79     -0.033604
328    8/8/2014  1090747      0.001395   97.52     -0.022748

[1224 rows x 5 columns]
           Date    Stock  Stock_change  Price  Price_change
327   8/15/2014  1090065     -0.000625  97.19     -0.003384
326   8/22/2014  1091487      0.001305  94.91     -0.023459
325   8/29/2014  1092964      0.001353  94.32     -0.006216
324    9/5/2014  1102718      0.008924  94.04     -0.002969
323   9/12/2014  1107620      0.004445  92.44     -0.017014
..          ...      ...           ...    ...           ...
4    10/23/2020  1391224     -0.002780  40.56      0.001481
3    10/30/2020  1376547     -0.010550  37.50     -0.075444
2     11/6/2020  1365069     -0.008338  37.91      0.010933
1    11/13/2020  1354914     -0.007439  40.87      0.078080
0    11/20/2020  1353844     -0.000790  41.70      0.020308

[306 rows x 5 columns]

In [139]:
def calc(history, index):
    last_week = history[-1:]
    return last_week['Stock_change'].iloc[0]

In [144]:
#calc is the function that evaluates each datapoint. 
def build(calc, train, test):
    history = train
    predictions = pd.DataFrame()
    for i in range(len(test)):
        predicted = calc(history, i)
        added_obj = test.iloc[i]
        print(added_obj)
        added_obj.Stock_change = predicted
        #predictions = predictions.append(added_obj)
        history = history.append(test.iloc[i])
    return predictions

In [145]:
l = build(calc, train, test)
l

Date             8/15/2014
Stock              1090065
Stock_change   -0.00062526
Price                97.19
Price_change   -0.00338392
Name: 327, dtype: object
Date             8/22/2014
Stock              1091487
Stock_change    0.00130451
Price                94.91
Price_change    -0.0234592
Name: 326, dtype: object
Date             8/29/2014
Stock              1092964
Stock_change     0.0013532
Price                94.32
Price_change   -0.00621642
Name: 325, dtype: object
Date              9/5/2014
Stock              1102718
Stock_change    0.00892436
Price                94.04
Price_change   -0.00296862
Name: 324, dtype: object
Date             9/12/2014
Stock              1107620
Stock_change    0.00444538
Price                92.44
Price_change     -0.017014
Name: 323, dtype: object
Date              9/19/2014
Stock               1108544
Stock_change    0.000834221
Price                 93.54
Price_change      0.0118996
Name: 322, dtype: object
Date             9/26/2014
Stock              1102727
Stock_change   -0.00524742
Price                92.39
Price_change    -0.0122942
Name: 321, dtype: object
Date             10/3/2014
Stock              1106434
Stock_change    0.00336167
Price                91.44
Price_change    -0.0102825
Name: 320, dtype: object
Date             10/10/2014
Stock               1107479
Stock_change    0.000944476
Price                 87.62
Price_change      -0.041776
Name: 319, dtype: object
Date            10/17/2014
Stock              1111871
Stock_change    0.00396576
Price                82.96
Price_change    -0.0531842
Name: 318, dtype: object
Date            10/24/2014
Stock              1103401
Stock_change   -0.00761779
Price                81.83
Price_change     -0.013621
Name: 317, dtype: object
Date            10/31/2014
Stock              1100972
Stock_change   -0.00220138
Price                81.26
Price_change   -0.00696566
Name: 316, dtype: object
Date             11/7/2014
Stock              1094691
Stock_change   -0.00570496
Price                78.24
Price_change    -0.0371647
Name: 315, dtype: object
Date            11/14/2014
Stock              1094727
Stock_change      3.29e-05
Price                76.51
Price_change    -0.0221115
Name: 314, dtype: object
Date            11/21/2014
Stock              1090051
Stock_change   -0.00427138
Price                75.38
Price_change    -0.0147693
Name: 313, dtype: object
Date            11/28/2014
Stock              1088914
Stock_change   -0.00104307
Price                72.43
Price_change     -0.039135
Name: 312, dtype: object
Date             12/5/2014
Stock              1096205
Stock_change    0.00669566
Price                67.18
Price_change    -0.0724838
Name: 311, dtype: object
Date            12/12/2014
Stock              1097390
Stock_change      0.001081
Price                61.11
Price_change    -0.0903543
Name: 310, dtype: object
Date            12/19/2014
Stock              1103824
Stock_change      0.005863
Price                55.79
Price_change    -0.0870561
Name: 309, dtype: object
Date             12/26/2014
Stock               1106648
Stock_change     0.00255838
Price                 55.74
Price_change   -0.000896218
Name: 308, dtype: object
Date             1/2/2015
Stock             1111801
Stock_change    0.0046564
Price               53.42
Price_change   -0.0416218
Name: 307, dtype: object
Date              1/9/2015
Stock              1121784
Stock_change    0.00897912
Price                48.75
Price_change    -0.0874204
Name: 306, dtype: object
Date             1/16/2015
Stock              1123888
Stock_change    0.00187558
Price                47.08
Price_change    -0.0342564
Name: 305, dtype: object
Date             1/23/2015
Stock              1125856
Stock_change    0.00175106
Price                46.52
Price_change    -0.0118946
Name: 304, dtype: object
Date            1/30/2015
Stock             1138099
Stock_change    0.0108744
Price               45.72
Price_change   -0.0171969
Name: 303, dtype: object
Date              2/13/2015
Stock               1138901
Stock_change   -0.000756298
Price                 51.14
Price_change     0.00967423
Name: 301, dtype: object
Date             2/20/2015
Stock              1141121
Stock_change    0.00194925
Price                51.79
Price_change     0.0127102
Name: 300, dtype: object
Date             2/27/2015
Stock              1143418
Stock_change    0.00201293
Price                49.53
Price_change    -0.0436378
Name: 299, dtype: object
Date              3/6/2015
Stock              1146528
Stock_change    0.00271991
Price                 50.4
Price_change     0.0175651
Name: 298, dtype: object
Date             3/13/2015
Stock              1153514
Stock_change    0.00609318
Price                47.67
Price_change    -0.0541667
Name: 297, dtype: object
Date             3/20/2015
Stock              1163991
Stock_change    0.00908268
Price                44.34
Price_change    -0.0698553
Name: 296, dtype: object
Date               4/3/2015
Stock               1182063
Stock_change      0.0127382
Price                 48.88
Price_change   -0.000204541
Name: 294, dtype: object
Date             4/10/2015
Stock              1189307
Stock_change    0.00612827
Price                51.79
Price_change     0.0595336
Name: 293, dtype: object
Date             4/17/2015
Stock              1198453
Stock_change    0.00769019
Price                54.81
Price_change     0.0583124
Name: 292, dtype: object
Date             4/24/2015
Stock              1205988
Stock_change    0.00628727
Price                56.54
Price_change     0.0315636
Name: 291, dtype: object
Date              5/1/2015
Stock              1212201
Stock_change    0.00515179
Price                58.28
Price_change     0.0307747
Name: 290, dtype: object
Date              5/8/2015
Stock              1206646
Stock_change   -0.00458257
Price                59.72
Price_change     0.0247083
Name: 289, dtype: object
Date             5/15/2015
Stock              1204157
Stock_change   -0.00206274
Price                60.01
Price_change      0.004856
Name: 288, dtype: object
Date             5/22/2015
Stock              1206389
Stock_change    0.00185358
Price                59.22
Price_change    -0.0131645
Name: 287, dtype: object
Date             5/29/2015
Stock              1213817
Stock_change    0.00615722
Price                58.38
Price_change    -0.0141844
Name: 286, dtype: object
Date            6/5/2015
Stock            1213870
Stock_change    4.37e-05
Price              59.65
Price_change    0.021754
Name: 285, dtype: object
Date             6/12/2015
Stock              1216610
Stock_change    0.00225724
Price                60.09
Price_change    0.00737636
Name: 284, dtype: object
Date             6/19/2015
Stock              1210028
Stock_change   -0.00541012
Price                59.89
Price_change   -0.00332834
Name: 283, dtype: object
Date             6/26/2015
Stock              1220363
Stock_change    0.00854113
Price                60.06
Price_change    0.00283854
Name: 282, dtype: object

c:\python\lib\site-packages\pandas\core\generic.py:5168: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value

Date              7/3/2015
Stock              1230939
Stock_change    0.00866627
Price                57.92
Price_change     -0.035631
Name: 281, dtype: object
Date             7/10/2015
Stock              1233897
Stock_change    0.00240304
Price                52.41
Price_change    -0.0951312
Name: 280, dtype: object
Date             7/17/2015
Stock              1236879
Stock_change    0.00241673
Price                51.69
Price_change    -0.0137378
Name: 279, dtype: object
Date              7/24/2015
Stock               1237005
Stock_change    0.000101869
Price                 49.26
Price_change      -0.047011
Name: 278, dtype: object
Date            7/31/2015
Stock             1236992
Stock_change    -1.05e-05
Price               47.96
Price_change   -0.0263906
Name: 277, dtype: object
Date              8/7/2015
Stock              1243009
Stock_change    0.00486422
Price                44.92
Price_change    -0.0633862
Name: 276, dtype: object
Date              8/14/2015
Stock               1243962
Stock_change    0.000766688
Price                 43.21
Price_change     -0.0380677
Name: 275, dtype: object
Date             8/21/2015
Stock              1246907
Stock_change    0.00236744
Price                41.38
Price_change    -0.0423513
Name: 274, dtype: object
Date             8/28/2015
Stock              1252526
Stock_change    0.00450635
Price                40.79
Price_change    -0.0142581
Name: 273, dtype: object
Date             9/11/2015
Stock              1264248
Stock_change    0.00672478
Price                45.16
Price_change    -0.0335973
Name: 271, dtype: object
Date             9/18/2015
Stock              1261218
Stock_change   -0.00239668
Price                45.46
Price_change    0.00664305
Name: 270, dtype: object
Date             9/25/2015
Stock              1264708
Stock_change    0.00276717
Price                45.52
Price_change    0.00131984
Name: 269, dtype: object
Date             10/2/2015
Stock              1267240
Stock_change    0.00200204
Price                45.01
Price_change    -0.0112039
Name: 268, dtype: object
Date             10/9/2015
Stock              1270600
Stock_change    0.00265143
Price                48.33
Price_change     0.0737614
Name: 267, dtype: object
Date            10/16/2015
Stock              1272064
Stock_change    0.00115221
Price                46.74
Price_change    -0.0328988
Name: 266, dtype: object
Date            10/23/2015
Stock              1268660
Stock_change   -0.00267597
Price                45.32
Price_change    -0.0303808
Name: 265, dtype: object
Date            10/30/2015
Stock              1266757
Stock_change   -0.00150001
Price                45.15
Price_change    -0.0037511
Name: 264, dtype: object
Date             11/6/2015
Stock              1269121
Stock_change    0.00186618
Price                45.97
Price_change     0.0181617
Name: 263, dtype: object
Date             11/13/2015
Stock               1269361
Stock_change    0.000189107
Price                 42.64
Price_change     -0.0724385
Name: 262, dtype: object
Date            11/20/2015
Stock              1271706
Stock_change    0.00184739
Price                40.82
Price_change    -0.0426829
Name: 261, dtype: object
Date            11/27/2015
Stock              1273841
Stock_change    0.00167885
Price                42.34
Price_change     0.0372366
Name: 260, dtype: object
Date             12/4/2015
Stock              1270276
Stock_change   -0.00279862
Price                 40.9
Price_change    -0.0340104
Name: 259, dtype: object
Date            12/11/2015
Stock              1275094
Stock_change    0.00379288
Price                36.94
Price_change    -0.0968215
Name: 258, dtype: object
Date            12/18/2015
Stock              1269935
Stock_change   -0.00404598
Price                35.77
Price_change     -0.031673
Name: 257, dtype: object
Date             12/25/2015
Stock               1269773
Stock_change   -0.000127566
Price                 36.62
Price_change      0.0237629
Name: 256, dtype: object
Date              1/1/2016
Stock              1278051
Stock_change    0.00651927
Price                37.08
Price_change     0.0125614
Name: 255, dtype: object
Date              1/8/2016
Stock              1288078
Stock_change    0.00784554
Price                34.63
Price_change    -0.0660734
Name: 254, dtype: object
Date              1/22/2016
Stock               1293511
Stock_change   -0.000847361
Price                 29.18
Price_change     -0.0460935
Name: 252, dtype: object
Date               2/5/2016
Stock               1303518
Stock_change    0.000325379
Price                 31.28
Price_change     -0.0282696
Name: 250, dtype: object
Date             2/19/2016
Stock              1302018
Stock_change   -0.00387123
Price                30.03
Price_change     0.0667851
Name: 248, dtype: object
Date             2/26/2016
Stock              1312140
Stock_change    0.00777409
Price                32.27
Price_change     0.0745921
Name: 247, dtype: object
Date               3/4/2016
Stock               1311750
Stock_change   -0.000297224
Price                 34.66
Price_change      0.0740626
Name: 246, dtype: object
Date             3/11/2016
Stock              1313377
Stock_change    0.00124033
Price                37.81
Price_change     0.0908829
Name: 245, dtype: object
Date             3/18/2016
Stock              1320209
Stock_change    0.00520186
Price                38.32
Price_change     0.0134885
Name: 244, dtype: object
Date             3/25/2016
Stock              1321574
Stock_change    0.00103393
Price                40.15
Price_change     0.0477557
Name: 243, dtype: object
Date               4/1/2016
Stock               1322018
Stock_change    0.000335963
Price                 38.22
Price_change     -0.0480697
Name: 242, dtype: object
Date              4/8/2016
Stock              1328711
Stock_change    0.00506271
Price                37.26
Price_change    -0.0251177
Name: 241, dtype: object
Date             4/22/2016
Stock              1333690
Stock_change    0.00405555
Price                42.08
Price_change     0.0206161
Name: 239, dtype: object
Date             4/29/2016
Stock              1335850
Stock_change    0.00161957
Price                44.79
Price_change     0.0644011
Name: 238, dtype: object
Date              5/6/2016
Stock              1334025
Stock_change   -0.00136617
Price                44.24
Price_change    -0.0122795
Name: 237, dtype: object
Date            5/13/2016
Stock             1333253
Stock_change   -0.0005787
Price               45.45
Price_change    0.0273508
Name: 236, dtype: object
Date              5/20/2016
Stock               1332379
Stock_change   -0.000655539
Price                 48.03
Price_change      0.0567657
Name: 235, dtype: object
Date             5/27/2016
Stock              1329747
Stock_change   -0.00197541
Price                49.01
Price_change     0.0204039
Name: 234, dtype: object
Date              6/3/2016
Stock              1334079
Stock_change    0.00325776
Price                48.91
Price_change    -0.0020404
Name: 233, dtype: object
Date              6/10/2016
Stock               1333636
Stock_change   -0.000332064
Price                 50.18
Price_change      0.0259661
Name: 232, dtype: object
Date             6/17/2016
Stock              1339096
Stock_change    0.00409407
Price                47.91
Price_change    -0.0452371
Name: 231, dtype: object
Date              6/24/2016
Stock               1337933
Stock_change   -0.000868496
Price                 49.02
Price_change      0.0231684
Name: 230, dtype: object
Date              7/1/2016
Stock              1341271
Stock_change    0.00249489
Price                48.28
Price_change    -0.0150959
Name: 229, dtype: object
Date              7/8/2016
Stock              1348469
Stock_change    0.00536655
Price                46.15
Price_change    -0.0441176
Name: 228, dtype: object
Date             7/15/2016
Stock              1351173
Stock_change    0.00200524
Price                45.59
Price_change    -0.0121343
Name: 227, dtype: object
Date             7/22/2016
Stock              1354090
Stock_change    0.00215886
Price                44.75
Price_change    -0.0184251
Name: 226, dtype: object
Date             7/29/2016
Stock              1356301
Stock_change    0.00163283
Price                42.14
Price_change     -0.058324
Name: 225, dtype: object
Date              8/5/2016
Stock              1359005
Stock_change    0.00199366
Price                40.83
Price_change    -0.0310869
Name: 224, dtype: object
Date             8/12/2016
Stock              1360648
Stock_change    0.00120897
Price                 43.1
Price_change     0.0555964
Name: 223, dtype: object
Date             8/19/2016
Stock              1367347
Stock_change    0.00492339
Price                47.17
Price_change     0.0944316
Name: 222, dtype: object
Date             8/26/2016
Stock              1371845
Stock_change    0.00328958
Price                47.38
Price_change    0.00445198
Name: 221, dtype: object
Date             9/2/2016
Stock             1357983
Stock_change   -0.0101046
Price               45.13
Price_change   -0.0474884
Name: 220, dtype: object
Date              9/9/2016
Stock              1363947
Stock_change    0.00439181
Price                45.96
Price_change     0.0183913
Name: 219, dtype: object
Date             9/16/2016
Stock              1357880
Stock_change   -0.00444812
Price                44.34
Price_change     -0.035248
Name: 218, dtype: object
Date              9/23/2016
Stock               1357504
Stock_change   -0.000276902
Price                 44.58
Price_change     0.00541272
Name: 217, dtype: object
Date            10/14/2016
Stock              1337407
Stock_change   -0.00284888
Price                50.44
Price_change     0.0185784
Name: 214, dtype: object
Date            10/21/2016
Stock              1328257
Stock_change    -0.0068416
Price                50.62
Price_change     0.0035686
Name: 213, dtype: object
Date            10/28/2016
Stock              1337021
Stock_change    0.00659812
Price                49.62
Price_change     -0.019755
Name: 212, dtype: object
Date            11/4/2016
Stock             1330107
Stock_change   -0.0051712
Price               45.52
Price_change    -0.082628
Name: 211, dtype: object
Date            11/11/2016
Stock              1337000
Stock_change    0.00518229
Price                44.95
Price_change     -0.012522
Name: 210, dtype: object
Date             11/18/2016
Stock               1336700
Stock_change   -0.000224383
Price                 45.16
Price_change     0.00467186
Name: 209, dtype: object
Date            11/25/2016
Stock              1336758
Stock_change      4.34e-05
Price                47.83
Price_change     0.0591231
Name: 208, dtype: object
Date             12/2/2016
Stock              1338118
Stock_change    0.00101739
Price                 48.9
Price_change     0.0223709
Name: 207, dtype: object
Date             12/9/2016
Stock              1336002
Stock_change   -0.00158132
Price                50.97
Price_change     0.0423313
Name: 206, dtype: object
Date            12/16/2016
Stock              1324122
Stock_change    -0.0088922
Price                51.93
Price_change     0.0188346
Name: 205, dtype: object
Date            12/23/2016
Stock              1311033
Stock_change   -0.00988504
Price                52.56
Price_change     0.0121317
Name: 204, dtype: object
Date            12/30/2016
Stock              1317260
Stock_change    0.00474969
Price                53.86
Price_change     0.0247336
Name: 203, dtype: object
Date              1/6/2017
Stock              1330891
Stock_change      0.010348
Price                53.34
Price_change   -0.00965466
Name: 202, dtype: object
Date            1/13/2017
Stock             1329108
Stock_change   -0.0013397
Price               52.08
Price_change    -0.023622
Name: 201, dtype: object
Date             1/20/2017
Stock              1338069
Stock_change    0.00674212
Price                51.84
Price_change    -0.0046083
Name: 200, dtype: object
Date             1/27/2017
Stock              1343633
Stock_change    0.00415823
Price                53.13
Price_change     0.0248843
Name: 199, dtype: object
Date              2/3/2017
Stock              1345340
Stock_change    0.00127044
Price                53.34
Price_change    0.00395257
Name: 198, dtype: object
Date             2/10/2017
Stock              1356807
Stock_change     0.0085235
Price                52.88
Price_change   -0.00862392
Name: 197, dtype: object
Date             2/17/2017
Stock              1346060
Stock_change    -0.0079208
Price                 53.2
Price_change    0.00605144
Name: 196, dtype: object
Date              2/24/2017
Stock               1346694
Stock_change    0.000471004
Price                 54.02
Price_change      0.0154135
Name: 195, dtype: object
Date              3/3/2017
Stock              1344454
Stock_change   -0.00166333
Price                53.57
Price_change   -0.00833025
Name: 194, dtype: object
Date            3/10/2017
Stock             1336547
Stock_change   -0.0058812
Price               50.88
Price_change   -0.0502147
Name: 193, dtype: object
Date              3/17/2017
Stock               1337877
Stock_change    0.000995102
Price                  48.5
Price_change     -0.0467767
Name: 192, dtype: object
Date             3/24/2017
Stock              1333887
Stock_change   -0.00298234
Price                47.85
Price_change    -0.0134021
Name: 191, dtype: object
Date              3/31/2017
Stock               1334977
Stock_change    0.000817161
Price                 49.31
Price_change       0.030512
Name: 190, dtype: object
Date              4/7/2017
Stock              1330350
Stock_change   -0.00346598
Price                51.27
Price_change     0.0397485
Name: 189, dtype: object
Date             4/14/2017
Stock              1328548
Stock_change   -0.00135453
Price                53.19
Price_change     0.0374488
Name: 188, dtype: object
Date             4/21/2017
Stock              1335003
Stock_change    0.00485869
Price                51.08
Price_change    -0.0396691
Name: 187, dtype: object
Date              4/28/2017
Stock               1336032
Stock_change    0.000770785
Price                 49.34
Price_change     -0.0340642
Name: 186, dtype: object
Date              5/5/2017
Stock              1332286
Stock_change   -0.00280382
Price                47.21
Price_change    -0.0431698
Name: 185, dtype: object
Date             5/12/2017
Stock              1336544
Stock_change    0.00319601
Price                47.06
Price_change   -0.00317729
Name: 184, dtype: object
Date             5/19/2017
Stock              1333099
Stock_change   -0.00257754
Price                49.25
Price_change     0.0465363
Name: 183, dtype: object
Date             5/26/2017
Stock              1327954
Stock_change   -0.00385943
Price                50.45
Price_change     0.0243655
Name: 182, dtype: object
Date             6/2/2017
Stock             1343664
Stock_change    0.0118302
Price                48.5
Price_change   -0.0386521
Name: 181, dtype: object
Date              6/9/2017
Stock              1350468
Stock_change    0.00506377
Price                46.56
Price_change         -0.04
Name: 180, dtype: object
Date             6/16/2017
Stock              1348545
Stock_change   -0.00142395
Price                45.29
Price_change    -0.0272766
Name: 179, dtype: object
Date             6/23/2017
Stock              1349383
Stock_change    0.00062141
Price                43.14
Price_change    -0.0474718
Name: 178, dtype: object
Date             6/30/2017
Stock              1335894
Stock_change   -0.00999642
Price                44.67
Price_change     0.0354659
Name: 177, dtype: object
Date              7/7/2017
Stock              1332087
Stock_change   -0.00284978
Price                45.49
Price_change     0.0183568
Name: 176, dtype: object
Date              7/14/2017
Stock               1321814
Stock_change    -0.00771196
Price                 45.51
Price_change    0.000439657
Name: 175, dtype: object
Date             7/21/2017
Stock              1312666
Stock_change   -0.00692079
Price                46.42
Price_change     0.0199956
Name: 174, dtype: object
Date              7/28/2017
Stock               1313557
Stock_change    0.000678771
Price                 48.35
Price_change      0.0415769
Name: 173, dtype: object
Date             8/4/2017
Stock             1308832
Stock_change   -0.0035971
Price               49.51
Price_change    0.0239917
Name: 172, dtype: object
Date             8/11/2017
Stock              1301666
Stock_change   -0.00547511
Price                49.11
Price_change   -0.00807918
Name: 171, dtype: object
Date            8/18/2017
Stock             1301666
Stock_change            0
Price                47.5
Price_change   -0.0327835
Name: 170, dtype: object
Date              8/25/2017
Stock               1300534
Stock_change   -0.000869655
Price                 47.74
Price_change     0.00505263
Name: 169, dtype: object
Date              9/1/2017
Stock              1306989
Stock_change    0.00496335
Price                 46.7
Price_change    -0.0217847
Name: 168, dtype: object
Date              9/8/2017
Stock              1308786
Stock_change    0.00137492
Price                 48.6
Price_change     0.0406852
Name: 167, dtype: object
Date             9/15/2017
Stock              1302423
Stock_change   -0.00486176
Price                49.08
Price_change    0.00987654
Name: 166, dtype: object
Date             9/22/2017
Stock              1297413
Stock_change   -0.00384668
Price                 50.2
Price_change     0.0228199
Name: 165, dtype: object
Date             9/29/2017
Stock              1291108
Stock_change   -0.00485967
Price                51.89
Price_change     0.0336653
Name: 164, dtype: object
Date             10/6/2017
Stock              1289708
Stock_change   -0.00108434
Price                50.21
Price_change    -0.0323762
Name: 163, dtype: object
Date            10/13/2017
Stock              1281177
Stock_change   -0.00661468
Price                51.07
Price_change     0.0171281
Name: 162, dtype: object
Date            10/20/2017
Stock              1269180
Stock_change   -0.00936405
Price                51.71
Price_change     0.0125318
Name: 161, dtype: object
Date            10/27/2017
Stock              1263539
Stock_change    -0.0044446
Price                52.62
Price_change     0.0175981
Name: 160, dtype: object
Date             11/3/2017
Stock              1254436
Stock_change   -0.00720437
Price                 54.6
Price_change     0.0376283
Name: 159, dtype: object
Date            11/10/2017
Stock              1257144
Stock_change    0.00215874
Price                57.13
Price_change      0.046337
Name: 158, dtype: object
Date            11/17/2017
Stock              1257120
Stock_change     -1.91e-05
Price                 55.9
Price_change    -0.0215298
Name: 157, dtype: object
Date            11/24/2017
Stock              1249581
Stock_change   -0.00599704
Price                56.98
Price_change     0.0193202
Name: 156, dtype: object
Date             12/1/2017
Stock              1247038
Stock_change   -0.00203508
Price                57.83
Price_change     0.0149175
Name: 155, dtype: object
Date             12/8/2017
Stock              1244574
Stock_change   -0.00197588
Price                57.02
Price_change    -0.0140066
Name: 154, dtype: object
Date            12/15/2017
Stock              1230309
Stock_change    -0.0114618
Price                57.21
Price_change    0.00333216
Name: 153, dtype: object
Date            12/22/2017
Stock              1221401
Stock_change   -0.00724046
Price                57.91
Price_change     0.0122356
Name: 152, dtype: object
Date            12/29/2017
Stock              1222737
Stock_change    0.00109383
Price                59.97
Price_change     0.0355724
Name: 151, dtype: object
Date              1/5/2018
Stock              1217289
Stock_change   -0.00445558

Empty DataFrame
Columns: []
Index: []